#!/bin/bash
path=$(dirname "$0":)

OPTIONS_FILE="/data/options.json"

if ! command -v jq &> /dev/null
then
    echo "jq could not be found. Please ensure it is installed."
    exit 1
fi
if [ ! -f "$OPTIONS_FILE" ]; then
    echo "options.json not found. The add-on may not be configured."
    exit 1
fi

mqtt=$(jq -r '.mqttserver' "$OPTIONS_FILE")
mqttuser=$(jq -r '.mqttuser' "$OPTIONS_FILE")
mqttpass=$(jq -r '.mqttpass' "$OPTIONS_FILE")
mqttport=$(jq -r '.mqttport' "$OPTIONS_FILE")
name=$(jq -r '.hassname' "$OPTIONS_FILE")

check()
{
"${path}"/heatpump info
}

mosquitto_sub -v -R -h "${mqtt}" -p "${mqttport}" -u "$mqttuser" -P "$mqttpass" -t homeassistant/# | while read line
do
	settemp=$(echo "${line}" | perl -lne '/my_heatpump_settemp\/state\s([0-9]*)/ and print ${1}')
	mode=$(echo "${line}" | perl -lne '/my_heatpump_mode_set\/state\s([0-9]*)/ and print ${1}')
	silent=$(echo "${line}" | perl -lne '/my_heatpump_silent\/set\s(.*)/ and print ${1}')
	if [[ -n "${settemp}" ]]; then
		"${path}"/heatpump temp "${settemp}"
		check
	fi
	if [[ -n "${silent}" ]]; then
		"${path}"/heatpump silent "${silent}"
		check
	fi	
	if [[ -n $mode ]]; then
		echo "${line}"
		if [[ $mode = "off" ]]; then
			"${path}"/heatpump off
			check
		elif [[ $mode = "heat" ]]; then
			"${path}"/heatpump on
			"${path}"/heatpump mode heat
			check
		elif [[ $mode = "auto" ]]; then
			"${path}"/heatpump on
			"${path}"/heatpump mode auto
			check
		elif [[ $mode = "cool" ]]; then
			"${path}"/heatpump on
			"${path}"/heatpump mode cool
			check
		fi
	fi

done
